apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos-deployment
  namespace: moshiri-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
      - name: memos
        image: ghcr.io/usememos/memos:latest
        ports:
        - containerPort: 5230
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: MEMOS_DRIVER
          value: "postgres"
        - name: MEMOS_DSN
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: MEMOS_DSN
---
apiVersion: v1
kind: Service
metadata:
  name: memos-service
  namespace: moshiri-app
spec:
  selector:
    app: memos
  ports:
  - port: 5230
    targetPort: 5230